In [3]:
import numpy as np

In [4]:
%timeit [i+1 for i in range(1000000)]

146 ms ± 52.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
%timeit np.arange(1000000) +1

5.42 ms ± 405 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Creation

In [6]:
array = np.array([1,2,3,4,5,6])
print(array)
print(type(array))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [7]:
array2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array2)
print(type(array2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [8]:
list = [1,2,3,4,5,6]
array3 = np.array(list)
print(array3)

[1 2 3 4 5 6]


In [9]:
array4 = np.arange(0,100)
print(array4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [10]:
array5 = np.linspace(1,100,7)
print(array5)

[  1.   17.5  34.   50.5  67.   83.5 100. ]


In [15]:
array6 = np.loadtxt("PracticeData\Practice2.txt", delimiter = ",")
print(array6)

[1. 2. 3. 4. 5. 6.]


In [12]:
array7 = np.empty((3,3))
print(array7)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
array8 = np.identity(4)
print(array8)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
