In [ ]:
import numpy as np

In [ ]:
%timeit [i+1 for i in range(1000000)]

In [ ]:
%timeit np.arange(1000000) +1

# Creation

In [ ]:
array = np.array([1,2,3,4,5,6])
print(array)
print(type(array))

In [ ]:
array2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array2)
print(type(array2))

In [ ]:
list = [1,2,3,4,5,6]
array3 = np.array(list)
print(array3)

In [ ]:
array4 = np.arange(0,100)
print(array4)

In [ ]:
array5 = np.linspace(1,100,7)
print(array5)

In [ ]:
array6 = np.loadtxt("PracticeData\Practice2.txt", delimiter = ",")
print(array6)

In [ ]:
array7 = np.empty((3,3))
print(array7)

In [ ]:
array8 = np.identity(4)
print(array8)

In [16]:
# Functions


In [36]:
func_Array = np.array([1,2,13,3,4,5,6], np.int8)
print(func_Array)
print(func_Array.dtype)
print(func_Array.shape)
print(func_Array.ndim)
print(func_Array.nbytes)
print(func_Array.argmax())
print(func_Array.argmin())
print(func_Array)
print(func_Array.argsort())
print(func_Array)

[ 1  2 13  3  4  5  6]
int8
(7,)
1
7
2
0
[ 1  2 13  3  4  5  6]
[0 1 3 4 5 6 2]
[ 1  2 13  3  4  5  6]


In [41]:
array9 = np.zeros(10)
print(array9)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [42]:
array10 = np.zeros((10,10))
print(array10)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [45]:
array11 = np.ones((10,10), np.int8 )
print(array11)
print(array11.dtype)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
int8


In [48]:
array12 = np.arange(99)
print(array12)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [49]:
array13 = array12.reshape(3,33)
print(array13)


[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]


In [50]:
print(array12.shape)
print(array13.shape)


(99,)
(3, 33)


In [62]:
array14= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array14)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
array_sum14a = np.sum(array14)
print(array_sum14a)
array_sum14b = np.sum(array14,axis=1)
print(array_sum14b)

45
[ 6 15 24]


In [64]:
print(func_Array+2)

[ 3  4 15  5  6  7  8]


In [65]:
print(array14.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
